### ISSUE TITLE
Last line not being deleted

### ISSUE THREAD

**Issue by TaiSHiNet** [harawata/sublime-delete-lines#1]
Whenever I try to delete last line, it'll just clear the text until BOL, while it should delete the line and bring the pointer previous line

**Comment by harawata** [comment]
This plugin mimics the behavior of 'Delete Line' key command in Eclipse and that's how it works, I believe (please correct me if I am wrong!).

Feel free to copy and modify my source and create your own plugin :-)

**Comment by TaiSHiNet** [comment]
You're right, I haven't used Eclipse and default (ST) Delete Line package works the same way.
I blow at coding but I'll try to get it done

Thanks!

**Comment by harawata** [comment]
You're welcome. Good luck! :smile:
